import {esc,date,STATUSES} from '../living-thesis/model.js';
import {companyLogoURL} from '../../core/company-catalog.js';
import {SECTORS,selectRows,reviewQueue} from './model.js';

export const numeric = n => Number.isFinite(n)?new Intl.NumberFormat('en-US',{maximumFractionDigits:4}).format(n):'—';
export const money = (n,currency='USD') => Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:2}).format(n):'—';
export const percent = n => Number.isFinite(n)?`${n.toFixed(1)}%`:'—';
const signed = (n,fmt) => Number.isFinite(n)?`${n>0?'+':''}${fmt(n)}`:'—';
const tone = n => Number.isFinite(n)?n>=0?'up':'down':'';
export const status = label => `<span class="pc-status ${label==='Overweight'?'pc-warn':label==='On target'?'pc-good':''}">${esc(label)}</span>`;
export function logo(tk,color) {
  const url=companyLogoURL(tk);
  return `<span class="pf-logo"><span class="pc-monogram" style="color:${color}">${esc(tk.slice(0,2))}</span>${url?`<img src="${url}" alt="" loading="lazy" data-pc-logo>`:''}</span>`;
}
function allocationLogo(tk,color) {
  const url=companyLogoURL(tk);
  return `<span class="pc-legend-logo" style="--logo-color:${color}" aria-hidden="true"><span>${esc(tk.slice(0,2))}</span>${url?`<img src="${url}" alt="" loading="lazy" data-pc-logo>`:''}</span>`;
}
const options = (rows,value) => rows.map(([id,label])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(label)}</option>`).join('');
export function appURL(app,symbol='') {
  const u=new URL(location.href);
  for(const key of ['symbol','thesis','book','portfolioView','company','stock'])u.searchParams.delete(key);
  u.searchParams.set('tab',app==='research'?'moatrices':app);u.searchParams.set('open',app);
  if(symbol)u.searchParams.set(app==='research'?'company':'stock',symbol);
  return `${u.pathname}${u.search}`;
}
function ring(snapshot,view) {
  const rows=view.group==='sector'?snapshot.sectors:snapshot.rows;
  const circumference=2*Math.PI*78;let offset=0;
  const arcs=rows.filter(r=>r.weight>0).map(r=>{
    const length=r.weight/100*circumference;
    const attr=view.group==='sector'?`data-pc-sector="${r.sec}"`:`data-pc-holding="${esc(r.tk)}"`;
    const chosen=view.group==='sector'?view.sector===r.sec:view.holding===r.tk;
    const arc=`<circle class="pf-arc ${chosen?'on':''}" ${attr} tabindex="0" role="button" aria-label="Filter ${esc(r.tk||r.name)} · ${percent(r.weight)}" aria-pressed="${chosen}" cx="110" cy="110" r="78" fill="none" stroke="${r.color}" stroke-width="24" stroke-dasharray="${Math.max(0,length-Math.min(3.4,length*.1))} ${circumference}" stroke-dashoffset="${-offset}"/>`;
    offset+=length;return arc;
  }).join('');
  return `<div class="pf-chart"><svg class="pf-ring" viewBox="0 0 220 220" role="group" aria-label="Allocation by ${view.group}"><circle class="pf-track" cx="110" cy="110" r="78" fill="none" stroke-width="24"/><g transform="rotate(-90 110 110)">${arcs}</g></svg><div class="pf-mid"><span class="pf-mid-k">${snapshot.total>0?'INVESTED ASSETS':'ALLOCATION'}</span><strong class="pf-mid-v">${snapshot.total>0?'100%':'—'}</strong><span class="pf-mid-s">${snapshot.rows.length} holdings · excludes cash</span></div></div>`;
}
export function holdingsTable(snapshot,view) {
  const rows=selectRows(snapshot.rows,view);
  return `<div class="pc-table-top"><span role="status">${rows.length} of ${snapshot.rows.length} holdings${view.holding?` · ${esc(view.holding)} selected`:''}</span><button data-pc-reset>Clear filters</button></div>
    ${!rows.length?`<div class="pc-empty"><b>${snapshot.rows.length?'No holdings match these filters':'Your portfolio starts here'}</b><p>${snapshot.rows.length?'Clear filters to see your complete book.':'Add your holdings to see allocation, targets and business reviews. Your data stays on this device.'}</p>${snapshot.rows.length?'':'<button class="lt-btn lt-primary" data-pc-add>Add your first holding</button>'}</div>`:`<table class="pc-table"><caption class="pc-sr">Holdings · entered prices and costs · weights use the complete portfolio</caption><thead><tr><th>Holding</th><th>Position<br><small>Shares / avg cost</small></th><th>Value<br><small>Entered price</small></th><th>Weight</th><th>Gain / Loss<br><small>Unrealized</small></th><th>Target</th><th>Thesis</th><th><span class="pc-sr">Details</span></th></tr></thead><tbody>${rows.map(r=>`<tr class="pf-row" data-tk="${esc(r.tk)}" data-row-id="${esc(r.h.id??r.tk)}">
      <td class="pc-company"><button class="pc-stock" data-pc-open="${esc(r.tk)}" aria-label="Open ${esc(r.tk)} stock detail">${logo(r.tk,r.color)}<span><b>${esc(r.tk)}</b><span>${esc(r.name)}</span><small><i style="background:${r.color}"></i>${SECTORS[r.sec].label}</small></span></button></td>
      <td data-label="Position"><b>${numeric(r.h.shares)}</b><small>${money(r.h.cost,r.currency)} avg</small></td>
      <td data-label="Current value"><b>${money(r.value,r.currency)}</b><small>${money(r.h.price,r.currency)} / share</small><small class="${r.stale?'pc-warn':''}">${r.priceAt?date(new Date(r.priceAt).toISOString()):'No price date'}${r.stale?' · Stale':''}</small></td>
      <td data-label="Portfolio weight"><b data-weight="${r.weight??''}">${percent(r.weight)}</b><div class="pc-weight"><i style="width:${r.weight??0}%;background:${r.color}"></i></div></td>
      <td data-label="Unrealized gain" class="${tone(r.gain)}"><b>${signed(r.gain,n=>money(n,r.currency))}</b><small>${signed(r.gainPercent,percent)}</small></td>
      <td data-label="Target weight"><button class="pc-target-link" data-pc-targets aria-label="Edit ${esc(r.tk)} target">${percent(r.target)}</button>${status(r.targetStatus)}</td>
      <td data-label="Living Thesis"><span class="pc-thesis">${esc(r.thesis)}</span><small>${r.company?.researchKind==='library'&&!r.company?.thesis.originalStatement?'Draft · review to adopt':r.company?.holding.lastUpdated?date(r.company.holding.lastUpdated):'Evidence unavailable'}</small></td>
      <td class="pc-open-cell"><button data-pc-open="${esc(r.tk)}" aria-label="Details for ${esc(r.tk)}">↗</button></td></tr>`).join('')}</tbody></table>`}`;
}
function targetsPanel(snapshot,view) {
  const rows=view.group==='sector'?snapshot.sectors:snapshot.rows;
  const total=Object.values(snapshot.targets[view.group==='sector'?'sectors':'holdings']).reduce((a,b)=>a+b,0);
  return `<section class="pc-card pc-targets"><div class="pc-card-head"><div><span class="pc-kicker">ALLOCATION PLAN</span><h2>Target vs actual</h2></div><button class="lt-btn" data-pc-targets>Set targets ↗</button></div><p class="pc-note">${view.group==='sector'?'Sector':'Holding'} targets · ${percent(total)} assigned · tolerance ±${snapshot.targets.tolerance} pp<br>User-defined · ${snapshot.targets.updatedAt?date(snapshot.targets.updatedAt):'No targets saved'}</p>
    <div class="pc-target-grid">${rows.length?rows.map(r=>`<div class="pc-target-row"><div><b>${esc(r.tk||r.name)}</b>${status(r.targetStatus)}</div><div class="pc-target-track"><i style="width:${r.weight??0}%;background:${r.color}"></i>${Number.isFinite(r.target)?`<span style="left:${r.target}%" title="Target ${r.target}%"></span>`:''}</div><p><span>Actual <b>${percent(r.weight)}</b></span><span>Target <b>${percent(r.target)}</b></span></p></div>`).join(''):'<p class="pc-note">Add a holding, then set your allocation plan.</p>'}</div></section>`;
}
export function cockpit(snapshot,bridge,view,{research=[],researchError='',message=''}={}) {
  const groups=view.group==='sector'?snapshot.sectors:snapshot.rows;
  const queue=reviewQueue(snapshot,bridge,research);
  const age=snapshot.oldest?date(new Date(snapshot.oldest).toISOString()):'Not recorded';
  const dataState=!snapshot.rows.length?'No holdings yet':!snapshot.compatible?'Multiple currencies · FX unavailable':snapshot.missing?`${snapshot.missing} unpriced holding(s) · allocation unavailable`:snapshot.stale?'Prices are stale':'Prices entered recently';
  return `<header class="pc-head"><div><div class="pc-kicker">MY PORTFOLIO / OVERVIEW</div><h1>Portfolio Cockpit<span>.</span></h1><p>Your holdings, your plan, your next review.</p></div><div class="pc-actions"><button class="lt-btn" data-pc-targets>Allocation settings</button><button class="lt-btn lt-primary pf-add">+ Add holding</button></div></header>
  ${message?`<p class="pc-message" role="status">${esc(message)}</p>`:''}${snapshot.targetError?`<p class="pc-warn" role="alert">Saved targets unavailable: ${esc(snapshot.targetError)} Open allocation settings to correct them.</p>`:''}
  <section class="pc-summary" aria-label="Portfolio summary"><div class="pc-summary-main"><span>Portfolio value <small>USD · holdings</small></span><strong class="pf-total">${money(snapshot.total)}</strong><small>Entered positions · cash excluded${snapshot.total===null?' · incomplete valuation':''}</small></div><div><span>Invested</span><strong>${money(snapshot.cost)}</strong><small>Cost basis of current holdings</small></div><div><span>Cash ready to invest</span><strong>—</strong><small>Broker balance unavailable</small></div><div><span>Gain / Loss</span><strong class="${tone(snapshot.gain)}">${signed(snapshot.gain,money)}</strong><small class="${tone(snapshot.gainPercent)}">${signed(snapshot.gainPercent,percent)} · unrealized</small></div></section>
  <button class="pf-asof ${snapshot.stale||snapshot.missing?'stale':''}" ${!snapshot.rows.length?'disabled':''}><span class="pf-dot"></span><span class="pf-asof-t"><b>${dataState}</b><small>Source: your entered prices · oldest ${age}${snapshot.undated?` · ${snapshot.undated} undated`:''} · weekday freshness check, market holidays excluded</small></span><span class="pf-asof-go">Update prices ↗</span></button>
  <div class="pc-visual-grid"><section class="pc-card pf-chart-card"><div class="pc-card-head"><div><span class="pc-kicker">THE COMPLETE BOOK</span><h2>Allocation</h2></div><div class="pc-toggle" aria-label="Allocation grouping">${['sector','holding'].map(g=>`<button data-pc-group="${g}" aria-pressed="${view.group===g}">${g==='sector'?'Sectors':'Holdings'}</button>`).join('')}</div></div><div class="pc-allocation-body">${ring(snapshot,view)}<div class="pc-legend">${groups.filter(r=>r.value!==0).map(r=>`<button ${view.group==='sector'?`data-pc-sector="${r.sec}" aria-pressed="${view.sector===r.sec}"`:`data-pc-holding="${esc(r.tk)}" aria-pressed="${view.holding===r.tk}"`}>${view.group==='sector'?`<i class="pc-legend-swatch" style="background:${r.color}"></i>`:allocationLogo(r.tk,r.color)}<span>${esc(r.tk||r.name)}<small>${view.group==='sector'?`${r.tks.length} holdings`:esc(r.name)}</small></span><b>${percent(r.weight)}</b></button>`).join('')||'<p class="pc-note">Allocation appears after you add priced holdings.</p>'}</div></div><p class="pc-note">Select a slice or label to filter Holdings. All weights use the complete portfolio.${snapshot.total===null?' Complete prices and one currency are required.':''}</p></section>
    <section class="pc-card pc-concentration"><div class="pc-card-head"><div><span class="pc-kicker">EXPOSURE CHECK</span><h2>Concentration</h2></div><span class="pc-live-dot"></span></div>${[3,5].map(n=>`<div class="pc-conc-row"><div><span>Top ${n} holdings</span><strong>${percent(snapshot[`top${n}`])}</strong></div><div class="pc-conc-track"><i style="width:${snapshot[`top${n}`]??0}%;background:${snapshot[`top${n}`]>snapshot.targets[`top${n}`]?'#d5aa68':'#79c9b4'}"></i><span style="left:${snapshot.targets[`top${n}`]}%"></span></div><small>Alert above ${snapshot.targets[`top${n}`]}%${snapshot[`top${n}`]>snapshot.targets[`top${n}`]?' · Above threshold':''}</small></div>`).join('')}<p class="pc-note">${snapshot.targets.updatedAt?'Your saved':'Default'} alert thresholds · adjustable in allocation settings. Based on entered holding values.</p><button class="pc-text-btn" data-pc-targets>Adjust thresholds ↗</button></section></div>
  <section class="pc-card pc-holdings"><div class="pc-card-head"><div><span class="pc-kicker">YOUR BUSINESSES</span><h2>Holdings</h2></div><span class="pc-note">Local portfolio · USD by default</span></div><div class="pc-filters"><label class="pc-search">Search holdings<input type="search" data-pc-view="query" placeholder="Ticker or company…" value="${esc(view.query)}"></label><label>Sector<select data-pc-view="sector">${options([['all','All sectors'],...Object.entries(SECTORS).map(([k,v])=>[k,v.label])],view.sector)}</select></label><label>Thesis<select data-pc-view="thesis">${options([['all','All thesis states'],...STATUSES.map(s=>[s,s])],view.thesis)}</select></label><label>Sort by<select data-pc-view="sort">${options([['weight','Weight · high to low'],['value','Value · high to low'],['gain','Gain · high to low'],['name','Company · A–Z']],view.sort)}</select></label></div><div class="pc-table-content">${holdingsTable(snapshot,view)}</div><p class="pc-note pc-table-source">Source: holdings entered on this device · prices dated per row. Gain excludes realized returns, dividends, fees and FX.</p></section>
  ${targetsPanel(snapshot,view)}
  <div class="pc-bottom-grid"><section class="pc-card pc-bridge"><div class="pc-card-head"><div><span class="pc-kicker">MONEY → PORTFOLIO</span><h2>Money bridge</h2></div><a class="pc-text-btn" href="${appURL('money')}">Open Money ↗</a></div><p class="pc-note">Source: Money ledger · THB · through ${bridge.asOf?date(bridge.asOf):'date unavailable'}</p><dl><div><dt>Total recorded cash<small>Cash + savings + investment reserve</small></dt><dd>${money(bridge.total,'THB')}</dd></div><div><dt>Investment reserve<small>Included in recorded cash · earmarked only</small></dt><dd>${money(bridge.reserve,'THB')}</dd></div><div><dt>Transferred to broker</dt><dd>— <small>Unavailable</small></dd></div><div><dt>Allocated to purchases</dt><dd>— <small>Unavailable</small></dd></div><div><dt>Ready to invest</dt><dd>— <small>Unavailable</small></dd></div></dl><p class="pc-note">${esc(bridge.reason)} THB ledger balances and USD holdings are shown separately; no FX conversion or combined total.</p></section>
  <section class="pc-card pc-review"><div class="pc-card-head"><div><span class="pc-kicker">NEXT ACTIONS</span><h2>ต้องตรวจสอบ <span class="pc-count">${queue.length}</span></h2></div></div><p class="pc-note">Checks cover the complete portfolio · thesis review every 30 days.</p><div class="pc-review-list">${queue.map((q,i)=>`<button data-pc-review="${i}" data-kind="${q.kind}"><span class="pc-review-dot"></span><span><b>${esc(q.title)}</b><small>${esc(q.note)}</small></span><span>↗</span></button>`).join('')||'<p class="pc-note">No alerts from available data. Missing evidence and broker cash still need to be connected.</p>'}</div>${researchError?`<p class="pc-warn" role="status">${esc(researchError)} <button data-pc-retry>Retry research</button></p>`:''}</section></div>
  <details class="pc-performance"><summary>Performance data coverage</summary><p>Unrealized gain uses your entered prices and current cost basis. Portfolio history, benchmark comparison, realized gains, dividends and currency gains are unavailable until dated prices, transactions and FX data are connected.</p></details><p class="pf-foot">Private portfolio · saved on this device · Auto mode remembers your latest view and filters.</p>`;
}
