// เนื้อหา 7 บท + ชิ้นส่วน + แหล่งอ้างอิง
// ข้อเท็จจริงทุกข้อมาจาก Apple (Newsroom 9 ก.ย. 2026 / หน้า iPhone Duo / หน้าสเปก) — `apple` คือวลีต้นฉบับ
// ตำแหน่งชิ้นส่วนภายในเป็นแบบจำลอง (ยังไม่มีการแกะเครื่องจริง) → ใส่ `model` บอกทุกชิ้นที่เดาตำแหน่ง

export const SRC = {
  news: { label: 'Apple Newsroom — Apple unveils iPhone Duo', url: 'https://www.apple.com/newsroom/2026/09/apple-unveils-iphone-duo/' },
  newsTh: { label: 'Apple Newsroom (ไทย) — Apple เผยโฉม iPhone Duo', url: 'https://www.apple.com/th/newsroom/2026/09/apple-unveils-iphone-duo/' },
  page: { label: 'Apple — iPhone Duo', url: 'https://www.apple.com/th/iphone-duo/' },
  specs: { label: 'Apple — iPhone Duo Tech Specs', url: 'https://www.apple.com/iphone-duo/specs/' },
};

export const CHAPTERS = [
  { id: 'closed', no: '01', en: 'THE DUO, CLOSED', short: 'ตัวเครื่อง',
    title: 'เล็กเท่า<br><em>พาสปอร์ต</em>',
    lead: 'ตอนพับ iPhone Duo หนา 11.3 มม. ขนาดใกล้พาสปอร์ต มีจอนอกให้ใช้เหมือนมือถือปกติ ลากแถบข้างล่างเพื่อหมุนดูด้านหลัง',
    control: { kind: 'slider', label: 'หมุนดูรอบเครื่อง', from: 'ด้านหน้า', to: 'ด้านหลัง' },
    parts: ['outer', 'centerstage', 'frame', 'touchid', 'cameractl', 'cameras', 'back'] },
  { id: 'open', no: '02', en: 'UNFOLD', short: 'กางออก',
    title: 'กางแล้ว<br><em>บางที่สุด</em>',
    lead: 'กางออกได้จอ 7.6 นิ้ว และบางแค่ 5.2 มม. เป็น iPhone ที่บางที่สุดเท่าที่ Apple เคยทำ ลากบานพับเพื่อพับหรือกาง',
    control: { kind: 'dial' }, parts: ['inner', 'thin', 'udc'] },
  { id: 'hinge', no: '03', en: 'THE HINGE', short: 'บานพับ',
    title: 'บานพับ <br><em>100 กว่าชิ้น</em>',
    lead: 'ชิ้นส่วนที่ทำให้เครื่องพับได้ซ่อนอยู่ใต้สันเครื่อง ลากแถบข้างล่างเพื่อยกชิ้นส่วนแต่ละชั้นขึ้นมาดู',
    control: { kind: 'slider', label: 'แยกชิ้นส่วนบานพับ', from: 'ประกอบ', to: 'แยกชิ้น' },
    parts: ['hcover', 'hlinks', 'hsupport', 'magnets'] },
  { id: 'glass', no: '04', en: 'THE FOLDING GLASS', short: 'จอพับ',
    title: 'พับกระจก<br><em>ยังไงไม่ให้แตก</em>',
    lead: 'ใครก็รู้ว่าจอพับมีรอยพับ แต่แทบไม่มีใครเคยเห็นว่าข้างในจอ แต่ละชั้น<b>ไถลผ่านกันเหมือนหน้าหนังสือ</b> ลากบานพับข้างล่าง แล้วดูในเลนส์ขยาย',
    control: { kind: 'dial' }, parts: [] },
  { id: 'inside', no: '05', en: 'UNDER THE BACK', short: 'ข้างใน',
    title: 'ข้างใน<br><em>มีอะไรบ้าง</em>',
    lead: 'เปิดฝาหลังดูข้างใน: แบตเตอรี่สองก้อน ระบบระบายความร้อน และชิปที่ Apple ออกแบบเองถึงสามตัว ลากแถบข้างล่างเพื่อแยกชั้น',
    control: { kind: 'slider', label: 'แยกชิ้นส่วนภายใน', from: 'ประกอบ', to: 'แยกชิ้น' },
    parts: ['backglass', 'magsafe', 'battery', 'vapor', 'board', 'c2', 'n1', 'cammod'] },
  { id: 'chip', no: '06', en: 'A20 PRO', short: 'ชิป A20 Pro',
    title: 'ชิป <br><em>2 นาโนเมตร</em>',
    lead: 'A20 Pro ตัวเดียวกับใน iPhone 18 Pro ผลิตด้วยเทคโนโลยี 2 นาโนเมตร ลากแถบเพื่อยกแผ่นระบายความร้อนออกแล้วดูผังภายในชิป',
    control: { kind: 'slider', label: 'เปิดแพ็กเกจชิป', from: 'ประกอบ', to: 'เปิด' },
    parts: ['super', 'effic', 'gpu', 'ane', 'pkg'] },
  { id: 'biz', no: '07', en: 'FOR THE SHAREHOLDER', short: 'ผู้ถือหุ้น',
    title: 'มุมของ <br><em>ผู้ถือหุ้น</em>',
    lead: 'วิศวกรรมทั้งหมดนี้มาพร้อมราคาเริ่มต้น $1,999 คำถามของนักลงทุนคือ มันเปลี่ยนเกมของธุรกิจ iPhone ได้แค่ไหน และอะไรที่ต้องจับตา',
    control: null, parts: [] },
];

export const PARTS = {
  // ---------- 01 ----------
  outer: { name: 'จอนอก 5.4 นิ้ว', cat: 'DISPLAY',
    body: 'ตอนพับก็ใช้งานได้เหมือนมือถือทั่วไป จอ OLED 5.4 นิ้ว ความละเอียด 460 ppi ให้พื้นที่จอราว 90% ของ iPhone 18 Pro ด้านหน้าปิดด้วย Ceramic Shield 2 ที่ทนรอยขีดข่วนขึ้น 3 เท่า',
    apple: '“provides 90 percent of the screen area of iPhone 18 Pro” · “Ceramic Shield 2 on the front has 3x better scratch resistance”', src: 'news' },
  centerstage: { name: 'กล้องหน้า Center Stage 12MP', cat: 'CAMERA',
    body: 'กล้องหน้าบนจอนอก ถ่ายรูปและวิดีโอได้ทุกแนวโดยไม่ต้องหมุนเครื่อง',
    apple: '“12MP Center Stage camera, ƒ/2.2 aperture”', src: 'specs', model: 'ตำแหน่งในโมเดลเป็นตัวอย่าง' },
  frame: { name: 'กรอบไทเทเนียม grade 5', cat: 'MATERIAL',
    body: 'กรอบทำจากไทเทเนียม grade 5 ขัดเงาแบบกระจก ตัวเครื่องใช้ไทเทเนียมรีไซเคิล 85% กันน้ำกันฝุ่นระดับ IP68',
    apple: '“grade 5 titanium” · “85% recycled titanium in the enclosure”', src: 'specs' },
  touchid: { name: 'ปุ่มข้าง + Touch ID', cat: 'BIOMETRICS',
    body: 'iPhone Duo ปลดล็อกด้วยลายนิ้วมือที่ฝังในปุ่มข้าง ไม่ใช่ Face ID',
    apple: '“Touch ID is integrated into the side button”', src: 'news', model: 'ตำแหน่งปุ่มในโมเดลเป็นตัวอย่าง' },
  cameractl: { name: 'Camera Control', cat: 'CONTROL',
    body: 'ปุ่มสัมผัสสำหรับเปิดกล้องและปรับค่าต่างๆ อยู่ข้างเครื่องร่วมกับปุ่มปรับเสียง',
    apple: '“Camera Control to quickly launch the camera”', src: 'news', model: 'ตำแหน่งปุ่มในโมเดลเป็นตัวอย่าง' },
  cameras: { name: 'กล้องหลัง 48MP สองตัว', cat: 'CAMERA',
    body: '48MP Fusion Main (26 มม. ƒ/1.6) ซูมออปติคอล 2x ในตัว คู่กับ 48MP Fusion Ultra Wide (13 มม. ƒ/2.2) ถ่ายวิดีโอ 4K120 Dolby Vision ได้',
    apple: '“48MP Fusion Main: 26 mm, ƒ/1.6 aperture” · “48MP Fusion Ultra Wide: 13 mm, ƒ/2.2 aperture”', src: 'specs' },
  back: { name: 'ฝาหลัง Ceramic Shield', cat: 'MATERIAL',
    body: 'ด้านหลังปิดด้วย Ceramic Shield และรองรับการชาร์จ MagSafe กับ Qi2 สูงสุด 25W',
    apple: '“Ceramic Shield protects the back” · “MagSafe wireless charging up to 25W”', src: 'news' },
  // ---------- 02 ----------
  inner: { name: 'จอใน 7.6 นิ้ว', cat: 'DISPLAY',
    body: 'จอ OLED แบบพับได้ 7.6 นิ้ว ใหญ่กว่าจอ iPhone 18 Pro Max 50% รองรับ ProMotion 120Hz สว่างสูงสุด 3000 nits กลางแจ้ง ผิวเคลือบ nano-texture ด้านช่วยลดแสงสะท้อน',
    apple: '“50 percent larger than iPhone 18 Pro Max” · “3000 nits of peak outdoor brightness”', src: 'news' },
  thin: { name: 'หนา 5.2 มม. ตอนกาง', cat: 'DESIGN',
    body: 'กางแล้วบางที่สุดเท่าที่ iPhone เคยมี ตอนพับหนา 11.3 มม. หนักทั้งเครื่อง 254 กรัม',
    apple: '“thinnest iPhone ever” · Open 0.21″ · Closed 0.44″ · 254 g', src: 'specs' },
  udc: { name: 'กล้อง FaceTime ใต้จอ', cat: 'CAMERA',
    body: 'กล้องหน้าของจอในซ่อนอยู่ใต้จอ ตอนไม่ใช้จะมองไม่เห็น ใช้วิดีโอคอลตอนกางเครื่อง',
    apple: '“new FaceTime camera stays hidden when not in use” · “Under-display FaceTime camera, ƒ/1.8”', src: 'news', model: 'ตำแหน่งในโมเดลเป็นตัวอย่าง' },
  // ---------- 03 ----------
  hcover: { name: 'ฝาครอบบานพับพิมพ์ 3D', cat: 'HINGE',
    body: 'สันเครื่องที่เห็นตอนพับคือฝาครอบที่พิมพ์ 3 มิติจากไทเทเนียมรีไซเคิล 100% ผิวพ่นทรายละเอียดให้ต่างจากกรอบขัดเงา',
    apple: '“3D-printed hinge cover with a contrasting micro-blasted finish” · “100 percent recycled titanium in the 3D-printed hinge cover”', src: 'news' },
  hlinks: { name: 'กลไกกว่า 100 ชิ้น', cat: 'HINGE',
    body: 'บานพับประกอบจากชิ้นส่วนมากกว่า 100 ชิ้น ทำหน้าที่คุมการพับและกางให้ลื่นและหนืดสม่ำเสมอ',
    apple: '“engineered from more than 100 components to precisely control opening and closing”', src: 'news', model: 'รูปทรงกลไกในโมเดลเป็นภาพอธิบาย ไม่ใช่แบบจริง' },
  hsupport: { name: 'ส่วนรองกลางจอ', cat: 'HINGE',
    body: 'ตอนกาง บานพับจะรองรับกลางจอให้แบนราบ ไม่ยุบตรงแนวพับ',
    apple: '“supports the center of the display to hold it flat when opened”', src: 'news', model: 'รูปทรงในโมเดลเป็นภาพอธิบาย' },
  magnets: { name: 'แม่เหล็กเรียงแถว', cat: 'HINGE',
    body: 'แม่เหล็กฝังในตัวเครื่องช่วยให้ปิดแล้วแนบสนิทและรู้สึกมั่นคง',
    apple: '“integrated magnet array, delivers a satisfying and secure closure”', src: 'news', model: 'ตำแหน่งแม่เหล็กในโมเดลเป็นตัวอย่าง' },
  // ---------- 05 ----------
  backglass: { name: 'ฝาหลัง', cat: 'ENCLOSURE',
    body: 'ยกฝาหลังของทั้งสองซีกออกเพื่อดูชิ้นส่วนข้างใน',
    apple: '“Ceramic Shield protects the back”', src: 'news' },
  magsafe: { name: 'MagSafe / Qi2', cat: 'POWER',
    body: 'ขดลวดชาร์จไร้สาย รองรับ MagSafe และ Qi2 สูงสุด 25W ชาร์จไร้สายได้ 50% ในราว 30 นาที',
    apple: '“MagSafe wireless charging up to 25W” · “wirelessly charge up to 50 percent in around 30 minutes”', src: 'specs', model: 'ตำแหน่งในโมเดลเป็นตัวอย่าง' },
  battery: { name: 'แบตเตอรี่สองก้อน', cat: 'POWER',
    body: 'แบตเตอรี่ความจุสูงข้างละหนึ่งก้อน การใช้ eSIM อย่างเดียวช่วยเพิ่มพื้นที่ให้แบตเตอรี่ ใช้ได้สูงสุด 24 ชั่วโมง และใช้โคบอลต์รีไซเคิล 100%',
    apple: '“one high-energy battery on each side” · “eSIM-only design … maximizes physical space for battery capacity”', src: 'news', model: 'ขนาดและรูปทรงในโมเดลเป็นตัวอย่าง' },
  vapor: { name: 'เวเปอร์แชมเบอร์', cat: 'THERMAL',
    body: 'แผ่นระบายความร้อนที่ Apple ออกแบบเอง ต่อตรงกับชิป A20 Pro ผ่านแพ็กเกจแบบใหม่ที่ได้แรงบันดาลใจจากชิปตระกูล M',
    apple: '“A new chip package inspired by M-series Apple silicon connects A20 Pro directly to a custom vapor chamber”', src: 'news', model: 'ขนาดในโมเดลเป็นตัวอย่าง' },
  board: { name: 'แผงวงจรหลัก + A20 Pro', cat: 'LOGIC BOARD',
    body: 'ชิป A20 Pro อยู่บนแผงวงจรหลักใต้เวเปอร์แชมเบอร์ รายละเอียดข้างในชิปดูต่อได้ในบทที่ 06',
    apple: '“built on the latest 2-nanometer process technology”', src: 'news', model: 'รูปทรงและตำแหน่งแผงวงจรเป็นตัวอย่าง (ยังไม่มีการแกะเครื่องจริง)' },
  c2: { name: 'โมเด็ม C2', cat: 'APPLE SILICON',
    body: 'โมเด็มเซลลูลาร์รุ่นใหม่ที่ Apple ออกแบบเอง รองรับ 5G และ mmWave ในสหรัฐฯ',
    apple: '“C2, Apple’s next-generation cellular modem system”', src: 'news', model: 'ตำแหน่งบนแผงเป็นตัวอย่าง' },
  n1: { name: 'ชิปไร้สาย N1', cat: 'APPLE SILICON',
    body: 'ชิปเครือข่ายไร้สายที่ Apple ออกแบบเอง ดูแล Wi‑Fi 7, Bluetooth 6 และ Thread',
    apple: '“N1, an Apple-designed wireless networking chip, enables Wi-Fi 7, Bluetooth 6, and Thread”', src: 'news', model: 'ตำแหน่งบนแผงเป็นตัวอย่าง' },
  cammod: { name: 'โมดูลกล้อง', cat: 'CAMERA',
    body: 'กล้องหลังใช้กันสั่นแบบเลื่อนเซนเซอร์ (sensor-shift) และเซนเซอร์ขนาดใหญ่',
    apple: '“large sensor, fast aperture, and sensor-shift optical image stabilization”', src: 'news', model: 'รูปทรงในโมเดลเป็นตัวอย่าง' },
  // ---------- 06 ----------
  super: { name: 'CPU: 2 super cores', cat: 'CPU',
    body: 'CPU 6 คอร์ แบ่งเป็นคอร์ประสิทธิภาพสูง 2 คอร์ Apple บอกว่า CPU เร็วขึ้นสูงสุด 20% จาก A19 Pro',
    apple: '“6‑core CPU with 2 super cores and 4 efficiency cores” · “up to 20 percent faster than A19 Pro”', src: 'specs', model: 'ผังชิปเป็นภาพอธิบาย ไม่ใช่ภาพ die จริง' },
  effic: { name: 'CPU: 4 efficiency cores', cat: 'CPU',
    body: 'คอร์ประหยัดพลังงาน 4 คอร์ ทำงานเบาๆ เบื้องหลังเพื่อให้แบตอยู่ได้นาน',
    apple: '“4 efficiency cores”', src: 'specs', model: 'ผังชิปเป็นภาพอธิบาย' },
  gpu: { name: 'GPU 7 คอร์', cat: 'GPU',
    body: 'GPU 7 คอร์ที่มี Neural Accelerators ในตัว เร็วขึ้นสูงสุด 40% และประหยัดพลังงานขึ้น',
    apple: '“7‑core GPU with Neural Accelerators” · “up to 40 percent faster and more power efficient”', src: 'specs', model: 'ผังชิปเป็นภาพอธิบาย' },
  ane: { name: 'Neural Engine 16 คอร์ แบบคู่', cat: 'AI',
    body: 'Neural Engine แบบคู่ (16 คอร์ × 2) ให้พลังประมวลผล AI เพิ่มขึ้น 2 เท่า',
    apple: '“new Dual 16-core Neural Engine offers 2x the compute power”', src: 'news', model: 'ผังชิปเป็นภาพอธิบาย' },
  pkg: { name: 'แพ็กเกจแบบชิป M + หน่วยความจำ', cat: 'PACKAGE',
    body: 'แพ็กเกจใหม่ได้แรงบันดาลใจจากชิปตระกูล M ต่อชิปเข้ากับเวเปอร์แชมเบอร์โดยตรง และแบนด์วิดท์หน่วยความจำเพิ่มขึ้น 50%',
    apple: '“new chip package inspired by M-series Apple silicon” · “50 percent more unified memory bandwidth”', src: 'news', model: 'การจัดวางในแพ็กเกจเป็นภาพอธิบาย' },
};

// บท 07 — ข้อเท็จจริงแยกจากมุมมองชัดเจน
export const BIZ = {
  facts: [
    ['ราคาเริ่มต้น', '$1,999', 'ความจุ 256GB · มีถึง 2TB'],
    ['พรีออเดอร์ / วางขาย', '16 / 23 ต.ค.', 'มากกว่า 70 ประเทศในรอบแรก'],
    ['ชิปที่ Apple ออกแบบเอง', '3 ตัว', 'A20 Pro · โมเด็ม C2 · ไร้สาย N1'],
  ],
  view: 'ยิ่ง Apple ออกแบบชิปหลักเองมากเท่าไร ก็ยิ่งคุมต้นทุนและคุณสมบัติของเครื่องได้เอง และพึ่งซัพพลายเออร์ภายนอกน้อยลง นี่คือคูเมืองแบบที่คู่แข่งลอกได้ยาก เพราะต้องลงทุนออกแบบชิปหลายปี',
  watch: [
    ['บานพับกับรอยพับหลังใช้งานจริง', 'เป็นมือถือพับรุ่นแรกของ Apple ถ้ามีรายงานบานพับเสียหรือรอยพับชัดขึ้นเร็วหลังวางขาย แบรนด์จะเจ็บกว่ารุ่นอื่น'],
    ['คนยอมจ่าย $1,999 แค่ไหน', 'ดูรายได้กลุ่ม iPhone ในงบไตรมาสแรกหลังวางขาย (ไตรมาส ต.ค.–ธ.ค. ซึ่ง Apple มักรายงานปลายเดือน ม.ค.)'],
    ['สิ่งที่ Apple ยังไม่เปิดเผย', 'ต้นทุนชิ้นส่วน ผู้ผลิตจอและชิป และยอดขาย ต้องรอการแกะเครื่องและงบการเงินจริง อย่าเชื่อตัวเลขลือ'],
  ],
};
