import {esc,date,tone,stale,reviewed,signed,metricChange} from './model.js';
import {icon,button,badge,logo,analysisLabel,score,number,sectionHead,provenance,evidenceRows,pillarName,empty,sellRows,questions} from './components.js';

export const TABS=[['thesis','book-open','Investment thesis'],['moat','table-2','Moat map'],['timeline','activity','Thesis drift'],['earnings','git-compare-arrows','Earnings diff'],['redteam','search','Red team'],['sell','bookmark','Sell conditions']];
export function detail(c,state) {
  const h=c.holding,t=c.thesis;
  return `<div class="lt-breadcrumb">${button('Portfolio Health','back','arrow-left','lt-quiet')}<span>/</span><span>${esc(h.symbol)}</span><span>/</span><span>Living thesis</span></div>
    <header class="lt-detail-head"><div class="lt-detail-identity">${logo(c)}<div><div class="lt-kicker">${esc(h.symbol)} <span class="lt-divider">/</span> ${esc(h.sector)}</div><h1>${esc(h.companyName)}</h1><p>${Number.isFinite(h.portfolioWeight)?`${h.portfolioWeight.toFixed(1)}% of ${c.isDemo?'sample ':''}portfolio`:'Portfolio weight unavailable'} · ${c.researchKind==='library'&&!t.originalStatement?'Research draft ready to review':'Owned with a thesis'}</p></div></div><div class="lt-head-actions">${button(reviewed(c)?'Reviewed':'Review thesis','review','check',reviewed(c)?'':'lt-primary')}${button(c.researchKind==='library'?'Refresh research':'Refresh analysis','refresh','activity','',state.loading?'disabled':'')}</div></header>
    <div class="lt-detail-stats"><div><span>${c.researchKind==='library'&&!t.originalStatement?'DRAFT STATUS':'THESIS STATUS'}</span>${badge(t.status)}</div><div><span>MOAT SCORE</span><strong>${number(t.moatScore)}<small> / 100</small></strong></div><div><span>CONFIDENCE</span><strong>${number(t.confidence,'%')}</strong></div><div><span>THESIS DRIFT</span><strong class="lt-${c.drift<0?'red':c.drift>0?'green':'muted'}">${c.drift===null?'—':signed(c.drift)}<small> pts since original</small></strong></div><div><span>EVIDENCE UPDATED</span><b>${date(h.lastUpdated)}</b><small class="${stale(h.lastUpdated)?'lt-amber':''}">${stale(h.lastUpdated)?'Stale · review source dates':c.isDemo?'Dated sample snapshot':'Dated source snapshot'}</small></div></div>
    <div class="lt-analysis-stamp"><span>${c.researchKind==='library'?'Source snapshot':'Analysis generated'} ${date(c.analysis?.generatedAt||c.thesis.updatedAt)}</span><span>${c.isDemo?'Demo analysis · Sample source dates remain unchanged':c.researchKind==='library'?'Research draft · Source dates unchanged · Not a live feed':'No analysis service connected'}</span></div>
    ${c.originalEdited?'<div class="lt-inline-notice lt-amber">Original thesis edited. The existing assessment has not evaluated your new statement. Evidence and pillar scores below refer to the saved research baseline.</div>':''}
    ${!c.isDemo&&c.researchKind!=='library'?'<div class="lt-inline-notice">Analysis unavailable · Add your original thesis and sell conditions. Verified evidence and an analysis service have not been connected.</div>':''}
    ${c.researchKind==='library'?`<details class="lt-methodology"><summary>Research draft · Sources & scoring method</summary><p>${esc(c.sourceNote)}</p><p>สถานะและทิศทางประเมินเทียบกับร่างในคลัง ไม่ใช่เหตุผลที่คุณซื้อ ผลตอบแทน หรือความน่าจะเป็นที่จะได้กำไร ไม่มีประวัติคะแนนจึงไม่สร้าง thesis drift ย้อนหลัง</p></details>`:''}
    <nav class="lt-tabs" role="tablist" aria-label="Living thesis sections" data-no-swipe>${TABS.map(([id,glyph,label])=>`<button role="tab" id="lt-tab-${id}" aria-controls="lt-panel" aria-selected="${state.tab===id}" tabindex="${state.tab===id?0:-1}" data-thesis-tab="${id}">${icon(glyph)}${label}${id==='sell'?` <small>${c.sellConditions.length}</small>`:''}</button>`).join('')}</nav>
    <div role="tabpanel" id="lt-panel" aria-labelledby="lt-tab-${state.tab}" tabindex="0">${({thesis:investment,moat:moatMap,timeline:timeline,earnings:earnings,redteam:redTeam,sell:sell})[state.tab](c)}</div>
    ${questions(c)}`;
}
function investment(c) {
  return `<div class="lt-thesis-grid"><div><section class="lt-section lt-original">${sectionHead(c.draftStatement&&!c.thesis.originalStatement?'ร่างเหตุผลในการถือ':'Why I bought it',c.draftStatement&&!c.thesis.originalStatement?'DRAFT · REVIEW BEFORE ADOPTING':'THE ORIGINAL THESIS',button(c.draftStatement&&!c.thesis.originalStatement?'Review & use draft':'Edit original','edit-thesis','book-open','lt-quiet'))}<blockquote>${esc(c.thesis.originalStatement||c.draftStatement)||'Write the reasons you chose to own this business.'}</blockquote><div class="lt-meta"><span>${c.originalEdited?'Edited on this device':c.draftStatement&&!c.thesis.originalStatement?'Not yet adopted':c.thesis.createdAt?`Established ${date(c.thesis.createdAt)}`:'Saved on this device'}</span><span>${c.isDemo?'Sample investor statement':c.draftStatement&&!c.thesis.originalStatement?'Suggested rationale · not your recorded reason':'Your investment rationale'}</span></div></section>
    <section class="lt-section">${sectionHead('Where the thesis stands','THE CURRENT ASSESSMENT')}<p class="lt-thesis-copy">${esc(c.thesis.currentSummary)}</p><div class="lt-change"><b>What has changed</b><p>${esc(c.changes)}</p></div>${provenance(c,{uncertainty:c.unknowns[0]})}</section>
    <section class="lt-section">${sectionHead('What must be true','KEY ASSUMPTIONS')}<div class="lt-assumptions">${c.assumptions.length?c.assumptions.map((a,i)=>`<article class="lt-assumption"><span class="lt-question-num">0${i+1}</span><div><div class="lt-assumption-title"><h3>${esc(a.title)}</h3><span class="lt-${a.state==='Supported'?'green':'amber'}">${esc(a.state)}</span></div><p>${esc(a.change)}</p>${provenance(c,a)}</div></article>`).join(''):empty('No assumptions documented','Start by writing your original thesis. Verified assumptions will be mapped here.')}</div></section></div>
    <aside class="lt-thesis-sidebar"><section class="lt-section">${sectionHead('Moat at a glance', '7 PILLARS',button('View map','tab-moat','arrow-up-right','lt-quiet'))}${c.pillars.map(p=>`<div class="lt-mini-pillar"><span>${esc(pillarName(p.type))}</span>${score(p.score)}<span class="lt-${tone(p.direction)}" title="${p.direction}">${p.direction==='improving'?'↗':p.direction==='weakening'?'↘':'→'}</span></div>`).join('')||'<p class="lt-muted">No pillar assessment available.</p>'}<p class="lt-caption">${c.isDemo?'Sample scores':'Scores'} summarize evidence, not investment returns.</p></section><section class="lt-unknowns">${sectionHead('Known unknowns','KEEP THE GAPS VISIBLE')}<ol>${c.unknowns.map(u=>`<li>${esc(u)}</li>`).join('')}</ol></section><section class="lt-red-preview"><div class="lt-kicker">${c.researchKind==='library'?'RESEARCH DRAFT':'ASTRA'} · RED TEAM ${c.isDemo?'· DEMO':''}</div><h2>Best Case Against<br>This Thesis</h2><p>${esc(c.redTeam[0]?.argument||'An honest counterargument needs verified evidence. No analysis is available yet.')}</p>${c.redTeam[0]?provenance(c,c.redTeam[0]):''}${button('Read the counterargument','tab-redteam','arrow-up-right','lt-quiet')}</section></aside></div>`;
}
function moatMap(c) {
  return `<section class="lt-section">${sectionHead('Moat Map','THE DURABILITY OF THE BUSINESS',`<span class="lt-meta">${number(c.thesis.moatScore)} / 100 overall</span>`)}<p class="lt-section-intro">Separate the source of the advantage from the evidence that it is enduring.</p><div class="lt-moat-list">${c.pillars.length?c.pillars.map((p,i)=>`<article class="lt-pillar"><div class="lt-pillar-top"><span class="lt-question-num">0${i+1}</span><h3>${esc(pillarName(p.type))}</h3>${score(p.score)}<span class="lt-pillar-direction lt-${tone(p.direction)}">${p.direction==='improving'?'↗':p.direction==='weakening'?'↘':'→'} ${p.direction}</span></div><div class="lt-pillar-body"><p>${esc(p.explanation)}</p><div class="lt-meta"><span>${p.confidence}% confidence</span><span>${p.evidenceIds.length} evidence ${p.evidenceIds.length===1?'event':'events'}</span><span>Updated ${date(p.updatedAt)}</span><span>${analysisLabel(c)}</span></div><p class="lt-uncertainty"><b>Still uncertain</b> ${esc(p.uncertainty)}</p>${evidenceRows(c,p.evidenceIds)}</div></article>`).join(''):empty('Moat analysis unavailable','The absence of evidence is not a zero moat score.')}</div></section>`;
}
function timeline(c) {
  return `<section class="lt-section">${sectionHead(c.researchKind==='library'?'Evidence & thesis observations':'Thesis Drift Timeline',c.researchKind==='library'?'DATED SOURCE OBSERVATIONS':'A RECORD OF CHANGING BELIEFS')}${c.researchKind==='library'?'<p class="lt-section-intro">วันที่ของแต่ละรายการอ้างอิงเอกสารหรือบทวิเคราะห์ที่ระบุ ไม่ใช่เหตุการณ์ใหม่ที่เกิดขึ้นวันนี้ ยังไม่มีประวัติคะแนนให้คำนวณ drift</p>':''}<div class="lt-timeline-legend"><span class="lt-green">● Strengthens</span><span class="lt-amber">● Mixed or uncertain</span><span class="lt-red">● Weakens</span><span class="lt-muted">● Neutral</span></div><div class="lt-timeline">${c.evidence.length?[...c.evidence].sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt)).map(e=>`<article class="lt-timeline-event"><time>${date(e.publishedAt)}</time><span class="lt-timeline-node lt-${tone(e.impact)}"></span><div><div class="lt-meta"><span>${esc(e.eventType.toUpperCase())}</span><span class="lt-${tone(e.impact)}">${e.impact.toUpperCase()} THESIS</span></div><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><div class="lt-meta"><span>${esc(pillarName(e.affectedPillar))}</span><span>${e.confidence}% confidence</span><span>${esc(e.sourceLabel)}</span></div><p class="lt-uncertainty"><b>Still uncertain</b> ${esc(e.uncertainty)}</p>${evidenceRows(c,[e.id])}</div></article>`).join(''):empty('No evidence yet','Meaningful earnings, product, customer and competitive events will appear here once evidence is connected.')}</div></section>`;
}
const METRICS=[['revenue','Revenue','money',true],['grossMargin','Gross margin','percent',true],['operatingMargin','Operating margin','percent',true],['freeCashFlow','Free cash flow','money',true],['customerGrowth','Customer growth','percent',true],['netRetention','Net retention','percent',true],['debt','Debt','money',false],['dilution','Share dilution','percent',false],['guidance','Guidance','text',null]];
function earnings(c) {
  if(c.earnings.length<2) return empty('Earnings comparison unavailable','Two comparable periods are required. Missing values are never treated as zero.');
  const [previous,current]=c.earnings.slice(-2);
  const amount=(value,unit)=>value===null||value===undefined?'Not available':unit==='money'?`$${value.toFixed(c.isDemo?1:2)}B`:unit==='ntd'?`NT$${value.toFixed(1)}B`:unit==='usd'?`$${value.toFixed(2)}`:unit==='percent'?`${value.toFixed(2)}%`:esc(value);
  return `<section class="lt-section">${sectionHead(c.researchKind==='library'?'What changed between these periods?':'What changed this quarter?','EARNINGS DIFF')}<p class="lt-thesis-copy">${esc(c.changes)}</p>${provenance(c,{uncertainty:c.unknowns[0]})}<div class="lt-periods"><span><small>PREVIOUS PERIOD</small>${esc(previous.period)}</span>${icon('git-compare-arrows')}<span><small>LATEST PERIOD</small>${esc(current.period)}</span></div><table class="lt-earnings"><thead><tr><th>Business metric</th><th>${esc(previous.period)}</th><th>${esc(current.period)}</th><th>Change</th><th>Thesis impact / ${c.researchKind==='library'?'Research interpretation':'Astra explanation'}</th></tr></thead><tbody>${(c.metrics||METRICS).map(([id,label,unit,higher])=>{
    const delta=unit==='text'?null:metricChange(current[id],previous[id],unit==='percent');
    const changed=unit==='text'?current[id]!==previous[id]:delta?.value!==0;
    const impact=c.metricImpacts?.[id] || (unit==='text'?changed?'Mixed':'Unchanged':!delta?'Insufficient data':!changed?'Unchanged':(delta.value>0)===higher?'Supports':'Contradicts');
    const color={Supports:'green',Contradicts:'red',Mixed:'amber'}[impact]||'muted';
    return `<tr><th>${esc(id==='customerGrowth'?c.customerLabel:label)}</th><td data-label="Previous">${amount(previous[id],unit)}</td><td data-label="Latest" class="lt-current">${amount(current[id],unit)}</td><td data-label="Change">${delta?`${signed(Number(delta.value.toFixed(1)))} ${delta.unit}`:unit==='text'?(changed?'Updated':'No change'):'—'}</td><td data-label="Thesis impact"><span class="lt-${color}">${impact}</span><p>${esc(c.metricNotes?.[id])}</p></td></tr>`;
  }).join('')}</tbody></table><p class="lt-caption">${esc(c.earningsCaption||'Mock data · USD billions unless indicated. Changes in rates are percentage points (pp). Comparisons are sequential and may be seasonal. Explanations use the dated sample earnings evidence above; none are verified research.')}</p></section>`;
}
function redTeam(c) {
  return `<section class="lt-section lt-redteam">${sectionHead('Best Case Against This Thesis',c.researchKind==='library'?'RESEARCH DRAFT · ADVERSARIAL REVIEW':'ASTRA · ADVERSARIAL REVIEW · '+(c.isDemo?'DEMO ANALYSIS':'UNAVAILABLE'))}<p class="lt-section-intro">A good thesis should survive its strongest opposition. Start with the argument you least want to be true.</p>${c.redTeam.length?c.redTeam.map((r,i)=>`<article class="lt-red-argument"><span class="lt-question-num">0${i+1}</span><div><h3>${esc(r.title)}</h3><p>${esc(r.argument)}</p>${provenance(c,r)}</div></article>`).join(''):empty('Red team analysis unavailable','A credible counterargument requires verified evidence. Begin with your most fragile assumption.')}</section>`;
}
function sell(c) {
  return `<section class="lt-section">${sectionHead('What Would Make Me Sell?','DECIDE BEFORE EMOTION DOES',button('Add condition','add-condition','bookmark'))}<p class="lt-section-intro">Define a change in the business that would invalidate your reasons for owning it. These conditions prompt a review; they do not place trades.</p><div class="lt-conditions">${sellRows(c)}</div></section>`;
}
