import {esc,date,average,needsReview,priority,selectHoldings,signed,stale} from './model.js';
import {icon,button,badge,logo,score,number,sparkline,sectionHead,empty} from './components.js';
export function overview(companies,state) {
  const selected=selectHoldings(companies,state.filter,state.sort,state.query);
  const review=companies.filter(needsReview);
  const signal=companies.flatMap(c=>c.evidence.map(e=>({c,e}))).sort((a,b)=>b.e.publishedAt.localeCompare(a.e.publishedAt)).slice(0,4);
  const stats=[['Holdings',companies.length,'businesses, not tickers',''],['Strengthened',companies.filter(c=>c.thesis.status==='STRENGTHENED').length,'theses gaining support','green'],['Weakened',companies.filter(c=>['WEAKENED','THESIS AT RISK'].includes(c.thesis.status)).length,'theses under pressure','red'],['Require review',review.length,'in your research queue','amber'],['Average moat',number(average(companies.map(c=>c.thesis.moatScore))),'out of 100',''],['Thesis confidence',number(average(companies.map(c=>c.thesis.confidence)),'%'),'evidence-based estimate','']];
  return `<header class="lt-page-head"><div><div class="lt-kicker">MATRICES <span class="lt-divider">/</span> THE LIVING THESIS</div><h1>Portfolio Health<span class="lt-title-dot">.</span></h1><p>Which holdings require your attention now?</p></div><div class="lt-head-actions">${button('Refresh analysis','refresh','activity','',state.loading?'disabled':'')}${button('Holdings & allocation','allocation','table-2','lt-quiet')}</div></header>
    <div class="lt-summary">${stats.map(([label,value,sub,color])=>`<div><span>${label}</span><strong class="${color?`lt-${color}`:''}">${value}</strong><small>${sub}</small></div>`).join('')}</div>
    ${companies.length?`<div class="lt-attention"><span class="lt-attention-icon">${icon(review.length?'activity':'check')}</span><div><b>${review.length?`${review.length} ${review.length===1?'business deserves':'businesses deserve'} a closer look`:'Your review queue is clear'}</b><p>${review.length?`${esc(review.map(c=>c.holding.symbol).join(' · '))} — ${review.some(c=>c.isDemo)?'revisit cash conversion and the durability of incremental returns.':'document the thesis and connect business evidence.'}`:'Keep testing the assumptions. A completed review is not proof that a thesis is safe.'}</p></div>${button('Open review queue','review-queue','arrow-up-right','lt-quiet')}</div>`:''}
    <section class="lt-section lt-holdings-section">${sectionHead('Your businesses',`${companies.length} HOLDINGS · ${state.scope==='demo'?'SAMPLE PORTFOLIO':'ON THIS DEVICE'}`)}
    <div class="lt-toolbar"><div class="lt-filters" data-no-swipe aria-label="Filter holdings">${['All','Strengthened','Unchanged','Weakened','At Risk','Needs Review'].map(f=>`<button data-filter="${f}" aria-pressed="${state.filter===f}">${f}${f==='All'?` <span>${companies.length}</span>`:''}</button>`).join('')}</div><div class="lt-search-sort"><label class="lt-search">${icon('search')}<input type="search" value="${esc(state.query)}" placeholder="Find a business" aria-label="Search holdings"></label><label class="lt-sort"><span class="lt-sr">Sort holdings</span><select aria-label="Sort holdings">${[['priority','Highest review priority'],['moat','Lowest moat score'],['drift','Biggest thesis drift'],['recent','Most recent update']].map(([v,t])=>`<option value="${v}" ${state.sort===v?'selected':''}>${t}</option>`).join('')}</select></label></div></div>
    ${!companies.length?empty('Your investment story starts here','Add a holding to document why you own it and the changes that would make you reconsider.',button('Add your first holding','allocation','table-2','lt-primary')+button('Explore demo portfolio','demo','book-open')):!selected.length?empty('No holdings match','Try another thesis status or clear your search.',button('Clear filters','clear','x')):`<table class="lt-holdings"><thead><tr><th>Company / weight</th><th>Thesis status</th><th>Moat score</th><th>Confidence</th><th>Latest signal</th><th>Review priority</th></tr></thead><tbody>${selected.map(c=>holdingRow(c)).join('')}</tbody></table>`}
    <div class="lt-table-foot"><span>${selected.length} of ${companies.length} businesses</span><span>Thesis drift = change in sample moat score since the original thesis</span></div></section>
    ${companies.length?`<div class="lt-overview-bottom"><section class="lt-section">${sectionHead('Recent thesis signals','THE BUSINESS, OVER TIME')}<div class="lt-signal-list">${signal.length?signal.map(({c,e})=>`<a class="lt-signal" href="${holdingURL(c.holding.symbol,state.scope,'timeline')}" data-symbol="${c.holding.symbol}" data-target-tab="timeline"><span class="lt-signal-date">${date(e.publishedAt).slice(0,6)}</span><span class="lt-event-dot lt-${e.impact==='weakens'?'red':e.impact==='strengthens'?'green':'amber'}"></span><span><b><span>${c.holding.symbol}</span> ${esc(e.title)}</b><small>${esc(e.sourceLabel)} · ${e.confidence}% confidence · ${esc(e.uncertainty)}</small></span>${icon('arrow-up-right')}</a>`).join(''):empty('No evidence yet','Connected evidence will appear here with dates and source labels.')}</div></section><aside class="lt-principle"><div class="lt-kicker">THE OWNER’S PERSPECTIVE</div>${icon('book-open')}<h2>Same business.<br>Still the same thesis?</h2><p>Price tells you what the market is doing. Evidence tells you whether the business you bought is changing.</p><div class="lt-principle-foot">Original belief <span>→</span> New evidence <span>→</span> Better questions</div></aside></div>`:''}`;
}
function holdingRow(c) {
  const h=c.holding,t=c.thesis,p=priority(c);
  return `<tr data-holding="${esc(h.symbol)}"><td><a class="lt-company-link" href="${holdingURL(h.symbol,c.isDemo?'demo':'personal')}" data-symbol="${esc(h.symbol)}">${logo(c)}<span><b>${esc(h.companyName)}</b><small><span class="lt-ticker">${esc(h.symbol)}</span> <span>${Number.isFinite(h.portfolioWeight)?`${h.portfolioWeight.toFixed(1)}% weight`:'Weight unavailable'}</span></small></span></a></td><td data-label="Thesis">${badge(t.status)}<small class="lt-cell-sub">${c.originalEdited?'Original thesis edited':c.drift===null?'Awaiting evidence':`${signed(c.drift)} pt thesis drift`}</small></td><td data-label="Moat">${score(t.moatScore)}${sparkline(c)}</td><td data-label="Confidence"><b class="lt-confidence">${number(t.confidence,'%')}</b><small class="lt-cell-sub">${t.confidence===null?'Not assessed':t.confidence>=80?'Higher confidence':'Moderate confidence'}</small></td><td class="lt-latest" data-label="Latest signal"><b>${esc(c.evidence[0]?.title||'No business evidence connected')}</b><small>${esc(c.questions.find(q=>q.status!=='resolved')?.title||'What must be true for this thesis to work?')}</small><span class="lt-cell-sub">${h.lastUpdated?`${date(h.lastUpdated)} · ${c.isDemo?'Sample evidence':'Evidence'}${stale(h.lastUpdated)?' · Stale':''}`:'Not yet updated'}</span></td><td data-label="Review"><span class="lt-priority lt-${p>=3?'amber':p?'neutral':'muted'}"><i></i>${p>=3?'High priority':p?'Needs review':c.reviewedAt?'Reviewed':'Routine'}</span><a class="lt-open" href="${holdingURL(h.symbol,c.isDemo?'demo':'personal')}" data-symbol="${esc(h.symbol)}" aria-label="Open ${esc(h.companyName)} living thesis">Open thesis ${icon('arrow-up-right')}</a></td></tr>`;
}
export function holdingURL(symbol,scope,tab='thesis') {
  const url=new URL(location.href);url.searchParams.set('symbol',symbol);url.searchParams.set('thesis',tab);url.searchParams.set('book',scope);url.searchParams.delete('portfolioView');return `${url.pathname}${url.search}`;
}
