// Service worker — precache app shell ทั้งหมด ใช้ offline ได้เต็มตัว
// เปลี่ยนไฟล์เมื่อไหร่ให้ bump VERSION เพื่อบังคับ cache ใหม่

const VERSION = "pp-os-v35";

const SHELL = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./css/base.css",
  "./css/desktop.css",
  "./css/window.css",
  "./css/taskbar.css",
  "./css/shell.css",
  "./css/apps.css",
  "./css/smart-money.css",
  "./js/main.js",
  "./js/core/window-manager.js",
  "./js/core/taskbar.js",
  "./js/core/app-shell.js",
  "./js/core/app-registry.js",
  "./js/core/storage.js",
  "./js/core/sync.js",
  "./js/core/ui.js",
  "./js/apps/notes.js",
  "./js/apps/todo.js",
  "./js/apps/weather.js",
  "./js/apps/money.js",
  "./js/apps/portfolio.js",
  "./js/apps/smart-money.js",
  "./js/core/smart-money-model.js",
  "./data/smart-money.json",
  "./js/apps/calculator.js",
  "./js/apps/discover.js",
  "./assets/brands/AAPL.svg",
  "./assets/brands/MCO.png",
  "./assets/brands/KHC.png",
  "./assets/brands/DVA.png",
  "./assets/brands/DAL.png",
  "./assets/brands/KR.png",
  "./assets/brands/ALLY.png",
  "./assets/brands/LEN.png",
  "./assets/brands/LLYVK.png",
  "./assets/brands/NYT.png",
  "./assets/brands/COF.png",
  "./assets/brands/LLYVA.png",
  "./assets/brands/LPX.png",
  "./assets/brands/NUE.png",
  "./assets/brands/NVR.png",
  "./assets/brands/JEF.png",
  "./assets/brands/DHI.png",
  "./assets/brands/AXP.png",
  "./assets/brands/GOOGL.png",
  "./assets/brands/NVDA.png",
  "./assets/brands/MSFT.png",
  "./assets/brands/COHR.png",
  "./assets/brands/SNPS.png",
  "./assets/brands/KO.png",
  "./assets/brands/BAC.png",
  "./assets/brands/INTC.png",
  "./assets/brands/SPACEX.svg",
  "./assets/brands/BLK.png",
  "./assets/brands/BN.png",
  "./assets/brands/AMZN.png",
  "./assets/brands/UBER.png",
  "./assets/brands/QSR.png",
  "./assets/brands/SPY.png",
  "./assets/brands/IVV.png",
  "./assets/brands/TSLA.png",
  "./assets/brands/WFC.png",
  "./assets/brands/BABA.png",
  "./assets/people/warren-buffett.jpg",
  "./assets/people/donald-trump.jpg",
  "./assets/people/charlie-munger.jpg",
  "./assets/people/ray-dalio.jpg",
  "./assets/people/cathie-wood.jpg",
  "./assets/people/george-soros.jpg",
  "./assets/people/nancy-pelosi.jpg",
  "./assets/brands/berkshire.svg",
  "./assets/brands/temasek.svg",
  "./assets/brands/pershing.svg",
  "./assets/brands/vanguard.svg",
  "./assets/brands/state-street.svg",
  "./assets/brands/jpmorgan.svg",
  "./assets/brands/morgan-stanley.svg",
  "./assets/brands/IVZ.png",
  "./assets/brands/CRWV.png",
  "./assets/brands/NOK.png",
  "./assets/brands/V.png",
  "./assets/brands/AVGO.png",
  "./assets/brands/AMD.png",
  "./assets/brands/TEM.png",
  "./assets/brands/HOOD.png",
  "./assets/brands/USB.png",
  "./assets/brands/TSM.png",
  "./assets/brands/GPN.png",
  "./assets/brands/MU.png",
  "./assets/brands/META.png",
  "./assets/brands/GS.png",
  "./assets/brands/DELL.png",
  "./assets/brands/OBDC.png",
  "./assets/brands/CVX.png",
  "./assets/brands/XOM.png",
  "./assets/brands/MRK.png",
  "./assets/credits.html",
  "./js/core/smart-money-sectors.js",
  "./data/smart-money-sectors.json",
  "./assets/brands/JNJ.png",
  "./assets/brands/CSCO.png",
  "./assets/brands/GM.png",
  "./assets/brands/LRCX.png",
  "./assets/brands/UNH.png",
  "./assets/brands/GE.png",
  "./assets/brands/AMAT.png",
  "./assets/brands/LLY.png",
  "./assets/brands/NWL.png",
  "./assets/brands/COST.png",
  "./assets/brands/PM.png",
  "./assets/brands/SIRI.png",
  "./assets/brands/CAT.png",
  "./assets/brands/TXN.png",
  "./assets/brands/ABBV.png",
  "./assets/brands/VZ.png",
  "./assets/brands/HD.png",
  "./assets/brands/M.png",
  "./assets/brands/WMT.png",
  "./assets/brands/RTX.png",
  "./assets/brands/MA.png",
  "./assets/brands/PG.png",
  "./assets/brands/MO.png",
  "./assets/brands/COTY.png",
  "./assets/brands/HRB.png",
  "./assets/brands/PH.png",
  "./assets/brands/LMT.png",
  "./assets/brands/TFC.png",
  "./assets/brands/OLN.png",
  "./assets/brands/ETN.png",
  "./assets/brands/KMI.png",
  "./assets/brands/CDNS.png",
  "./assets/brands/VTR.png",
  "./assets/brands/TMUS.png",
  "./assets/brands/CCL.png",
  "./assets/brands/JBL.png",
  "./assets/brands/CTAS.png",
  "./assets/brands/TT.png",
  "./assets/brands/MTZ.png",
  "./assets/brands/IBM.png",
  "./assets/brands/MCD.png",
  "./assets/brands/BA.png",
  "./assets/brands/TMO.png",
  "./assets/brands/DUK.png",
  "./assets/brands/PLTR.png",
  "./assets/brands/SNDK.png",
  "./assets/brands/TJX.png",
  "./assets/brands/WY.png",
  "./assets/brands/OXY.png",
  "./assets/brands/URI.png",
  "./assets/brands/FIS.png",
  "./assets/brands/CMCSA.png",
  "./assets/brands/MOD.png",
  "./assets/brands/PFE.png",
  "./assets/brands/AMGN.png",
  "./assets/brands/PNC.png",
  "./assets/brands/CRM.png",
  "./assets/brands/CVS.png",
  "./assets/brands/LIN.png",
  "./assets/brands/STX.png",
  "./assets/brands/PEP.png",
  "./assets/brands/NFLX.png",
  "./assets/brands/VRTX.png",
  "./assets/brands/PTC.png",
  "./assets/brands/SCHW.png",
  "./assets/brands/FFIV.png",
  "./assets/brands/ACN.png",
  "./assets/brands/UNP.png",
  "./assets/brands/GLW.png",
  "./assets/brands/PANW.png",
  "./assets/brands/ADI.png",
  "./assets/brands/GILD.png",
  "./assets/brands/ABT.png",
  "./assets/brands/SO.png",
  "./assets/brands/COP.png",
  "./assets/brands/FAST.png",
  "./assets/brands/WELL.png",
  "./assets/brands/SBUX.png",
  "./assets/brands/FDS.png",
  "./assets/brands/GEV.png",
  "./assets/brands/ANET.png",
  "./assets/brands/AJG.png",
  "./assets/brands/ICE.png",
  "./assets/brands/VLO.png",
  "./assets/brands/RSG.png",
  "./assets/brands/PSX.png",
  "./assets/brands/BMY.png",
  "./assets/brands/MPC.png",
  "./assets/brands/JCI.png",
  "./assets/brands/EW.png",
  "./assets/brands/EQIX.png",
  "./assets/brands/ROK.png",
  "./assets/brands/PWR.png",
  "./assets/brands/TRV.png",
  "./assets/brands/BX.png",
  "./assets/brands/ABNB.png",
  "./assets/brands/MCK.png",
  "./assets/brands/VRSN.png",
  "./assets/brands/WM.png",
  "./assets/brands/CB.png",
  "./assets/brands/QCOM.png",
  "./assets/brands/CL.png",
  "./assets/brands/ORCL.png",
  "./assets/brands/HCA.png",
  "./assets/brands/TGT.png",
  "./assets/brands/UPS.png",
  "./assets/brands/HLT.png",
  "./assets/brands/WDC.png",
  "./assets/brands/PAYX.png",
  "./assets/brands/ITW.png",
  "./assets/brands/CRWD.png",
  "./assets/brands/IBKR.png",
  "./assets/brands/PYPL.png",
  "./assets/brands/DBX.png",
  "./assets/brands/RBLX.png",
  "./assets/brands/T.png",
  "./assets/brands/MORN.png",
  "./assets/brands/CLNE.png",
  "./assets/references/trump-holdings-3.png",
  "./assets/references/trump-holdings-4.png",
  "./assets/references/trump-holdings-5.png",
  "./assets/references/trump-holdings-6.png",
  "./assets/references/trump-holdings-7.png",
  "./assets/references/trump-holdings-8.png",
  "./assets/references/trump-holdings-9.png",
  "./assets/references/trump-holdings-10.png",
  "./assets/references/trump-holdings-11.png",
  "./assets/references/trump-holdings-12.png",
  "./assets/references/trump-holdings-13.png",
  "./assets/references/trump-holdings-14.png",
  "./assets/references/trump-holdings-15.png",
  "./assets/references/trump-holdings-16.png",
  "./assets/references/pelosi-holdings-1.png",
  "./assets/references/pelosi-holdings-2.png",
  "./assets/references/pelosi-holdings-3.png",
  "./assets/references/trump-holdings-1.png",
  "./assets/references/trump-holdings-2.png",
  "./assets/icons/favicon.svg",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./assets/icons/apple-touch-icon.png",
  "./assets/fonts/inter-var-latin.woff2",
  "./assets/fonts/instrument-serif-400-latin.woff2",
  "./assets/fonts/ibm-plex-mono-500-latin.woff2",
  "./assets/fonts/sarabun-400-thai.woff2",
  "./assets/fonts/sarabun-600-thai.woff2",
  "./assets/fonts/ibm-plex-sans-thai-600-thai.woff2",
  "./assets/fonts/ibm-plex-sans-thai-700-thai.woff2",
];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(SHELL)));
  self.skipWaiting();
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("pp-os-") && k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  const url = new URL(req.url);
  if (req.method !== "GET" || url.origin !== location.origin) return;

  // Moatrices ถูกฝังเป็น iframe ใน More และอยู่ origin เดียวกัน — ถ้าไม่กันไว้
  // ทุกหน้าที่เปิดในเว็บจะไหลเข้ามาอยู่ใน cache ของแอป (บวม + เสิร์ฟหน้าเก่าตอนออฟไลน์)
  const scope = new URL(self.registration.scope).pathname;
  if (!url.pathname.startsWith(scope)) return;

  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then(
      (hit) =>
        hit ??
        fetch(req).then((res) => {
          // เก็บเฉพาะ response ที่ใช้ได้จริง — 404/500 ระหว่าง deploy ถ้าถูก cache
          // จะค้างถาวรจนกว่าจะ bump VERSION (ผู้ใช้เห็นหน้าพังโดยรีเฟรชเท่าไหร่ก็ไม่หาย)
          if (res.ok && res.type === "basic") {
            const copy = res.clone();
            caches.open(VERSION).then((c) => c.put(req, copy));
          }
          return res;
        })
    )
  );
});
