import {esc} from '../../core/ui.js';
import {amountText as money,monthName,dateName,shiftMonth,localDate,category,balances,monthTotals,cashFlow,budgetRows,selectEntries,allocatedToGoals,monthlyBills,subscriptionSummary} from './model.js';
export {esc};
const paths={
  wallet:'<path d="M20 8V5H5a2 2 0 0 0 0 4h15v11H5a2 2 0 0 1-2-2V7"/><path d="M20 12h-5v5h5"/><path d="M17 14.5h.01"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  arrow:'<path d="M7 17 17 7M7 7h10v10"/>',
  down:'<path d="M12 4v16M6 14l6 6 6-6"/>',
  up:'<path d="M12 20V4M6 10l6-6 6 6"/>',
  chart:'<path d="M4 3v17h17M8 16v-4M13 16V7M18 16v-7"/>',
  list:'<path d="M8 6h12M8 12h12M8 18h12M4 6h.01M4 12h.01M4 18h.01"/>',
  budget:'<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M4 10h16M10 10v10"/>',
  target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
  search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  circle:'<circle cx="12" cy="12" r="8"/>',
  close:'<path d="m6 6 12 12M18 6 6 18"/>',
  left:'<path d="m14 6-6 6 6 6"/>',
  right:'<path d="m10 6 6 6-6 6"/>',
  edit:'<path d="m16 3 5 5-12 12H4v-5Z M13 6l5 5"/>',
  download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
  upload:'<path d="M12 16V4m-5 5 5-5 5 5M4 16v5h16v-5"/>',
  settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="currentColor"/><circle cx="15" cy="17" r="3" fill="currentColor"/>',
  calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 11h18M7 15h3M14 15h3"/>',
  flag:'<path d="M5 21V4c5-4 9 4 14 0v10c-5 4-9-4-14 0"/>',
  shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
  coffee:'<path d="M4 8h12v7a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4ZM16 9h2a3 3 0 0 1 0 6h-2M3 22h16M7 2v3M12 2v3"/>',
  home:'<path d="m3 10 9-7 9 7M5 9v12h14V9M10 21v-7h4v7"/>',
  transport:'<rect x="4" y="4" width="16" height="14" rx="3"/><path d="M4 12h16M8 18l-2 3M16 18l2 3M8 15h.01M16 15h.01"/>',
  health:'<path d="M9 3h6v6h6v6h-6v6H9v-6H3V9h6Z"/>',
  fun:'<path d="m9 4 12 8-12 8Z"/>',
  work:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12h18M10 12v3h4v-3"/>',
};
export const icon=name=>`<svg class="mn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.wallet}</svg>`;
export const button=(label,action,glyph='',kind='',extra='')=>`<button type="button" class="mn-btn ${kind}" data-action="${action}" ${extra}>${glyph?icon(glyph):''}${label}</button>`;
export const miniButton=(label,action,glyph,extra='')=>button('',action,glyph,'mn-icon-btn',`aria-label="${esc(label)}" title="${esc(label)}" ${extra}`);
export const pill=(text,tone='')=>`<span class="mn-pill ${tone}">${text}</span>`;
const catIcon=cat=>({Food:'coffee',Transport:'transport',Home:'home',Fun:'fun',Health:'health',Salary:'work',Investments:'chart'}[cat]||'wallet');
const catColor=cat=>({Food:'mint',Transport:'blue',Home:'amber',Fun:'violet',Health:'coral',Salary:'mint',Investments:'blue'}[cat]||'muted');
export const empty=(title,copy,action='',glyph='list')=>`<div class="mn-empty">${icon(glyph)}<h3>${title}</h3><p>${copy}</p>${action}</div>`;
const sectionHead=(title,subtitle='',action='')=>`<div class="mn-section-head"><div><h2>${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div>${action}</div>`;
const percent=value=>Number.isFinite(value)?`${Math.round(value)}%`:'—';
const progress=(value,label,tone='')=>`<div class="mn-progress ${tone}" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(Math.min(100,Math.max(0,value)))}"><span style="width:${Math.min(100,Math.max(0,value))}%"></span></div>`;
export const TABS=[['overview','Overview','chart'],['transactions','Transactions','list'],['budgets','Budgets','budget'],['goals','Goals','target'],['subscriptions','Subscriptions','calendar']];

export function summary(data,state) {
  const balance=balances(data.entries),m=monthTotals(data.entries,state.month);
  const rows=[['Recorded balance',balance.total,'All transactions through today',''],['Income',m.income,monthName(state.month),'mn-positive'],['Expenses',m.expense,`${m.count} transaction${m.count===1?'':'s'} this month`,''],['Net cash flow',m.net,m.rate===null?'Add income to calculate savings rate':`${percent(m.rate)} of income retained`,m.net<0?'mn-negative':'mn-positive']];
  return `<section class="mn-summary" aria-label="Money summary">${rows.map(([label,value,note,tone],i)=>`<div><span>${label}${i===0?pill('THB'):''}</span><strong class="${tone}" data-metric="${i}" title="${money(value)}">${money(value)}</strong><small>${note}</small></div>`).join('')}</section>`;
}
export function attention(data,state) {
  const rows=budgetRows(data.entries,data.budgets,state.month),over=rows.filter(r=>r.status==='over');
  const unreviewed=data.entries.filter(e=>e.reviewed!==true && e.date.startsWith(state.month)).length;
  const b=balances(data.entries),allocated=allocatedToGoals(data.goals);
  if (allocated>b.savings) return `<aside class="mn-attention">${icon('flag')}<div><b>Savings goals need a closer look</b><p>${money(allocated-b.savings)} more is assigned to goals than the savings allocation currently holds.</p></div>${button('Review goals','goals','arrow','mn-quiet')}</aside>`;
  if (over.length) return `<aside class="mn-attention">${icon('flag')}<div><b>${over.length} spending categor${over.length===1?'y is':'ies are'} over budget</b><p>${esc(over.map(r=>r.cat).join(', '))} · ${money(over.reduce((s,r)=>s-r.left,0))} above the limits you set.</p></div>${button('Review budgets','budgets','arrow','mn-quiet')}</aside>`;
  if (unreviewed) return `<aside class="mn-attention mn-attention-neutral">${icon('circle')}<div><b>A quick check-in keeps your money clear</b><p>${unreviewed} transaction${unreviewed===1?'':'s'} to review in ${monthName(state.month)}.</p></div>${button('Review transactions','review-queue','arrow','mn-quiet')}</aside>`;
  return '';
}
export function chartPanel(data,state) {
  const rows=cashFlow(data.entries,state.month,state.range),max=Math.max(...rows.flatMap(r=>[r.income,r.expense]),1);
  const hasData=rows.some(r=>r.count),period=rows.reduce((a,r)=>a+r.net,0);
  return `<section class="mn-panel mn-flow">${sectionHead('Cash flow','Income and spending, side by side',`<div class="mn-segment" aria-label="Chart period">${[6,12].map(n=>`<button type="button" data-action="range" data-range="${n}" aria-pressed="${state.range===n}">${n}M</button>`).join('')}</div>`)}
    <div class="mn-flow-total"><strong class="${period<0?'mn-negative':''}">${money(period)}</strong><span>net over ${state.range} months</span></div>
    ${hasData?`<div class="mn-chart" aria-label="Monthly income and expense chart"><div class="mn-chart-axis"><span>${money(max,true)}</span><span>${money(max/2,true)}</span><span>฿0</span></div><div class="mn-chart-bars">${rows.map(r=>`<button type="button" class="mn-bar-group ${r.month===state.month?'is-current':''}" data-action="chart-month" data-month="${r.month}" aria-label="${monthName(r.month)}: income ${money(r.income)}, expenses ${money(r.expense)}. View month."><span class="mn-bars"><i class="mn-bar-in" style="height:${r.income/max*100}%"></i><i class="mn-bar-out" style="height:${r.expense/max*100}%"></i></span><span class="mn-bar-label">${monthName(r.month,true).split(' ')[0]}</span><span class="mn-chart-tip"><b>${monthName(r.month)}</b><span>Income ${money(r.income)}</span><span>Expenses ${money(r.expense)}</span></span></button>`).join('')}</div></div>`:empty('Your cash flow starts here','Record your first transaction to see money coming in and going out.',button('Add transaction','add','plus','mn-primary'),'chart')}
    <div class="mn-chart-foot"><div class="mn-legend"><span><i></i>Income</span><span><i></i>Expenses</span></div><details><summary>View chart data</summary><table><caption>Monthly cash flow in THB</caption><thead><tr><th>Month</th><th>Income</th><th>Expenses</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${monthName(r.month,true)}</td><td>${money(r.income)}</td><td>${money(r.expense)}</td></tr>`).join('')}</tbody></table></details></div>
    ${allocations(data)}
  </section>`;
}
function allocations(data) {
  const b=balances(data.entries);
  const transferred=(data.transfers||[]).reduce((sum,t)=>sum+Number(t.amount||0),0);
  return `<div class="mn-allocations"><div class="mn-allocation-head"><span>YOUR ALLOCATIONS</span>${button('Manage','settings','','mn-text')}</div><div class="mn-allocation-grid">${[['cash','Available cash','wallet'],['savings','Savings','target'],['invest','Set aside to invest','chart'],['transferred','Transferred to portfolio','up']].map(([key,label,glyph])=>`<div>${icon(glyph)}<span>${label}</span><strong class="${(b[key]??transferred)<0?'mn-negative':''}">${money(key==='transferred'?transferred:b[key])}</strong></div>`).join('')}</div><div class="mn-allocation-actions">${button('Record portfolio transfer','add-transfer','up','mn-text')}<a href="portfolio.html?portfolioView=allocation&amp;book=personal">Open Portfolio allocation ${icon('arrow')}</a></div><p>Earmarked from your recorded income. Transfers are tracked separately and are not added to portfolio value automatically.</p></div>`;
}
function budgetPreview(data,state) {
  const rows=budgetRows(data.entries,data.budgets,state.month).filter(r=>r.limit>0||r.spent>0).sort((a,b)=>b.spent-a.spent).slice(0,4);
  return `<section class="mn-panel">${sectionHead('Spending plan',monthName(state.month),button('View all','budgets','arrow','mn-text'))}${rows.length?rows.map(r=>`<button type="button" class="mn-budget-mini" data-action="budget" data-cat="${esc(r.cat)}"><span class="mn-category-icon mn-${catColor(r.cat)}">${icon(catIcon(r.cat))}</span><span><b>${esc(r.cat)}</b><small>${r.limit?`${money(r.spent)} of ${money(r.limit)}`:`${money(r.spent)} · Set a budget`}</small>${progress(r.ratio===null?0:r.ratio*100,r.cat+' budget',r.status==='over'?'mn-negative':r.status==='near'?'mn-amber':'')}</span><em class="${r.status==='over'?'mn-negative':''}">${r.ratio===null?'—':percent(r.ratio*100)}</em></button>`).join(''):empty('Give your spending a plan','Set a monthly limit for the categories that matter to you.',button('Set budgets','budgets','plus','mn-quiet'),'budget')}</section>`;
}
function goalsPreview(data) {
  return `<section class="mn-panel">${sectionHead('Working toward',`${data.goals.length} savings goal${data.goals.length===1?'':'s'}`,button('View goals','goals','arrow','mn-text'))}${data.goals.length?data.goals.slice(0,2).map(g=>`<button type="button" class="mn-goal-mini" data-action="fund" data-id="${esc(g.id)}"><div>${icon('target')}<b>${esc(g.name)}</b><span>${percent(g.saved/g.target*100)}</span></div>${progress(g.saved/g.target*100,g.name)}<small>${money(g.saved)} <span>of ${money(g.target)}</span></small></button>`).join(''):empty('Make room for what matters','Name a goal and start assigning savings to it.',button('Create a goal','add-goal','plus','mn-quiet'),'target')}</section>`;
}
export function transactionTable(entries,{overview=false}={}) {
  if(!entries.length) return empty(overview?'No transactions this month':'No matching transactions',overview?'Add income or an expense to start your ledger.':'Try a different month or clear your filters.',button(overview?'Add transaction':'Clear filters',overview?'add':'clear','plus','mn-quiet'));
  return `<div class="mn-table-wrap"><table class="mn-transactions"><thead><tr><th>Transaction</th><th>Date</th><th>Category</th><th>Amount</th><th><span class="mn-sr-only">Review and edit</span></th></tr></thead><tbody>${entries.map(e=>`<tr data-entry="${esc(e.id)}"><td><button type="button" class="mn-transaction-name" data-action="edit" data-id="${esc(e.id)}"><span class="mn-category-icon mn-${catColor(category(e))}">${icon(catIcon(category(e)))}</span><span><b>${esc(e.note||category(e))}</b><small>${e.type==='in'?'Income':'Expense'}${e.roundup?` · ${money(e.roundup)} to savings`:''}${e.date>localDate()?' · Future-dated':''}</small></span></button></td><td class="mn-cell-date">${dateName(e.date)}</td><td class="mn-cell-category">${pill(esc(category(e)))}</td><td class="mn-cell-amount ${e.type==='in'?'mn-positive':''}">${e.type==='in'?'+':'−'}${money(e.amount)}</td><td class="mn-row-actions">${miniButton(e.reviewed?'Mark as unreviewed':'Mark as reviewed','toggle-review',e.reviewed?'check':'circle',`data-id="${esc(e.id)}" aria-pressed="${e.reviewed===true}"`)}${miniButton('Edit transaction','edit','edit',`data-id="${esc(e.id)}"`)}</td></tr>`).join('')}</tbody></table></div>`;
}
export function billsPanel(data,state) {
  const bills=monthlyBills(data.recurring,state.month,data.entries),today=localDate(),unpaid=bills.filter(b=>!b.payment);
  return `<section class="mn-panel mn-bills">${sectionHead('Subscriptions & bills',`${unpaid.length} unpaid · ${money(unpaid.reduce((s,b)=>s+b.amount,0))}`,`${button('View all','subscriptions','arrow','mn-text')}${miniButton('Add subscription','add-subscription','plus')}`)}${bills.length?`<div class="mn-bill-list">${bills.map(b=>`<div class="mn-bill" data-bill="${esc(b.id)}"><span class="mn-bill-day"><small>${monthName(b.dueDate.slice(0,7),true).split(' ')[0]}</small><b>${Number(b.dueDate.slice(-2))}</b></span><button type="button" class="mn-bill-name" data-action="edit-bill" data-id="${esc(b.id)}"><b>${esc(b.name)}</b><small class="${!b.payment&&b.dueDate<today?'mn-amber':''}">${b.payment?'Recorded':b.dueDate<today?'Past due':b.dueDate===today?'Due today':'Upcoming'} · Monthly</small></button><div><strong>${money(b.amount)}</strong>${b.payment?pill('Paid','mn-positive'):button('Record','pay-bill','','mn-text',`data-id="${esc(b.id)}" data-month="${b.month}"`)}</div></div>`).join('')}</div>`:empty('Keep the next bill in sight','Add rent, subscriptions, or another monthly bill.',button('Add a subscription','add-subscription','plus','mn-quiet'),'calendar')}<p class="mn-panel-note">Reminders you add yourself. A bill becomes an expense when you record its payment.</p></section>`;
}
export function subscriptions(data,state) {
  const s=subscriptionSummary(data.recurring,state.month,data.entries),today=localDate();
  return `<div class="mn-page-intro">${sectionHead('Subscriptions','Keep regular commitments visible before they renew.',button('Add subscription','add-subscription','plus','mn-primary'))}</div><div class="mn-sub-summary"><div><span>Active subscriptions</span><strong>${s.active}</strong><small>Monthly reminders on this device</small></div><div><span>Monthly commitment</span><strong>${money(s.monthly)}</strong><small>Based on active reminders</small></div><div><span>Annualized</span><strong>${money(s.annual)}</strong><small>A planning estimate, not a statement</small></div><div><span>Due this month</span><strong class="${s.unpaid.length?'mn-amber':'mn-positive'}">${s.unpaid.length}</strong><small>${s.unpaid.length?money(s.unpaid.reduce((sum,b)=>sum+b.amount,0))+' still to record':'Everything recorded'}</small></div></div>${s.active?`<section class="mn-panel mn-subscriptions"><div class="mn-section-head"><div><h2>${monthName(state.month)} schedule</h2><p>Record a payment when it leaves your account.</p></div><div class="mn-sub-filter"><span>${s.occurrences.filter(b=>b.payment).length} paid</span><span>${s.occurrences.filter(b=>!b.payment).length} remaining</span></div></div><div class="mn-sub-list">${s.occurrences.map(b=>`<article class="mn-subscription ${b.payment?'is-paid':''}" data-bill="${esc(b.id)}"><div class="mn-sub-date"><small>${monthName(b.dueDate.slice(0,7),true).split(' ')[0]}</small><strong>${Number(b.dueDate.slice(-2))}</strong></div><div class="mn-sub-main"><button type="button" data-action="edit-bill" data-id="${esc(b.id)}"><b>${esc(b.name)}</b><small>${esc(b.cat||'Other')} · Monthly · ${b.payment?'Payment recorded':b.dueDate<today?'Past due':b.dueDate===today?'Due today':'Upcoming'}</small></button><div class="mn-sub-meta"><strong>${money(b.amount)}</strong>${b.payment?pill('Paid','mn-positive'):button('Record payment','pay-bill','','mn-text',`data-id="${esc(b.id)}" data-month="${b.month}"`)}</div></div></article>`).join('')}</div><p class="mn-panel-note">Subscriptions are reminders you add yourself. They do not create transactions until you record the payment.</p></section>`:empty('No subscriptions yet','Add your regular bills and renewals so they appear before they surprise you.',button('Add your first subscription','add-subscription','plus','mn-primary'),'calendar')}`;
}
export function overview(data,state) {
  return `${summary(data,state)}${attention(data,state)}<div class="mn-overview-grid"><div class="mn-main-column">${chartPanel(data,state)}<section class="mn-panel mn-recent">${sectionHead('Recent transactions',monthName(state.month),button('View all','transactions','arrow','mn-text'))}${transactionTable(selectEntries(data.entries,{month:state.month}).slice(0,5),{overview:true})}</section></div><aside class="mn-side-column">${budgetPreview(data,state)}${goalsPreview(data)}${billsPanel(data,state)}</aside></div>`;
}
export function transactions(data,state) {
  const rows=selectEntries(data.entries,{...state,month:state.allDates?'':state.month});
  const net=rows.reduce((s,e)=>s+(e.type==='in'?e.amount:-e.amount),0);
  const cats=[...new Set(data.entries.map(category))].sort();
  return `<div class="mn-page-intro">${sectionHead('Your transactions','Every entry, with room for the details.',`${button('Import CSV','import','upload','mn-quiet')}${button('Export CSV','export','download','mn-quiet')}`)}</div><div class="mn-transaction-tools"><label class="mn-search">${icon('search')}<input type="search" aria-label="Search transactions" data-control="query" value="${esc(state.query)}" placeholder="Search notes, categories, amounts…"></label><div class="mn-segment" aria-label="Transaction type">${[['all','All'],['in','Income'],['out','Expenses']].map(([key,label])=>`<button type="button" data-action="filter" data-type="${key}" aria-pressed="${state.type===key}">${label}</button>`).join('')}</div></div><div class="mn-filter-row"><label>Category<select aria-label="Filter category" data-control="cat"><option value="all">All categories</option>${cats.map(cat=>`<option ${state.cat===cat?'selected':''}>${esc(cat)}</option>`).join('')}</select></label><label>Status<select aria-label="Review status" data-control="review">${[['all','All statuses'],['pending','Needs review'],['reviewed','Reviewed']].map(([v,l])=>`<option value="${v}" ${state.review===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Sort<select aria-label="Sort transactions" data-control="sort">${[['newest','Newest first'],['oldest','Oldest first'],['largest','Largest amount']].map(([v,l])=>`<option value="${v}" ${state.sort===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="mn-check"><input type="checkbox" data-control="allDates" ${state.allDates?'checked':''}>All dates</label></div><div class="mn-results"><span>${rows.length} transaction${rows.length===1?'':'s'} · ${state.allDates?'All dates':monthName(state.month)}</span><span>Filtered net <b class="${net<0?'mn-negative':'mn-positive'}">${money(net)}</b></span></div><section class="mn-panel mn-ledger">${transactionTable(rows.slice(0,state.shown))}${rows.length>state.shown?`<div class="mn-load-more">${button(`Show more (${rows.length-state.shown} remaining)`,'more','','mn-quiet')}</div>`:''}</section>`;
}
export function budgets(data,state) {
  const rows=budgetRows(data.entries,data.budgets,state.month),limit=rows.reduce((s,r)=>s+r.limit,0),used=rows.filter(r=>r.limit>0).reduce((s,r)=>s+r.spent,0),unbudgeted=rows.filter(r=>!r.limit).reduce((s,r)=>s+r.spent,0);
  return `<div class="mn-page-intro">${sectionHead('A plan for your spending',`Monthly limits apply to every month until you change them. Viewing ${monthName(state.month)}.`,button('Add category budget','add-budget','plus','mn-quiet'))}</div><div class="mn-budget-summary"><div><span>Monthly budget</span><strong>${money(limit)}</strong></div><div><span>Spent in budgeted categories</span><strong>${money(used)}</strong></div><div><span>${limit-used<0?'Over budget':'Budget remaining'}</span><strong class="${limit-used<0?'mn-negative':'mn-positive'}">${money(Math.abs(limit-used))}</strong></div><div><span>Spending without a budget</span><strong>${money(unbudgeted)}</strong></div></div><div class="mn-budget-grid">${rows.map(r=>`<article class="mn-panel mn-budget-card" data-budget="${esc(r.cat)}"><div class="mn-budget-card-head"><span class="mn-category-icon mn-${catColor(r.cat)}">${icon(catIcon(r.cat))}</span><h2>${esc(r.cat)}</h2>${miniButton('Edit '+r.cat+' budget','budget','edit',`data-cat="${esc(r.cat)}"`)}</div><div class="mn-budget-numbers"><strong>${money(r.spent)}</strong><span>${r.limit?'of '+money(r.limit):'No limit set'}</span></div>${progress((r.ratio||0)*100,r.cat+' budget',r.status==='over'?'mn-negative':r.status==='near'?'mn-amber':'')}<div class="mn-budget-card-foot"><span class="${r.status==='over'?'mn-negative':r.status==='near'?'mn-amber':''}">${r.limit?r.left<0?money(-r.left)+' over budget':money(r.left)+' remaining':'Give this category a monthly limit'}</span>${pill(r.status==='unset'?'Not set':r.status==='over'?'Over budget':r.status==='near'?'Near limit':'Within budget',r.status==='over'?'mn-negative':r.status==='near'?'mn-amber':'')}</div></article>`).join('')}</div>`;
}
export function goals(data) {
  const b=balances(data.entries),assigned=allocatedToGoals(data.goals),free=b.savings-assigned;
  return `<div class="mn-page-intro">${sectionHead('Save with something in mind','Assign your savings to the things you care about.',button('New goal','add-goal','plus','mn-quiet'))}</div><div class="mn-goal-summary"><span class="mn-goal-summary-icon">${icon('target')}</span><div><span>Unassigned savings</span><strong class="${free<0?'mn-negative':''}">${money(free)}</strong><p>${money(assigned)} assigned to goals · ${money(b.savings)} total savings allocation</p></div>${button('Manage allocations','settings','settings','mn-quiet')}</div>${free<0?'<p class="mn-inline-warning">Your assigned goals exceed recorded savings. Release goal funds or review the transactions that changed your savings.</p>':''}<div class="mn-goal-grid">${data.goals.length?data.goals.map(g=>`<article class="mn-panel mn-goal-card" data-goal="${esc(g.id)}"><div class="mn-goal-card-head"><span class="mn-category-icon mn-mint">${icon('target')}</span>${pill(g.saved>=g.target?'Funded':'In progress',g.saved>=g.target?'mn-positive':'')}${miniButton('Edit '+g.name,'edit-goal','edit',`data-id="${esc(g.id)}"`)}</div><h2>${esc(g.name)}</h2><div class="mn-goal-amount"><strong>${money(g.saved)}</strong><span>of ${money(g.target)}</span></div>${progress(g.saved/g.target*100,g.name)}<div class="mn-goal-progress-label"><span>${money(Math.max(0,g.target-g.saved))} to go</span><span>${percent(g.saved/g.target*100)}</span></div>${button('Manage funds','fund','plus','mn-quiet',`data-id="${esc(g.id)}"`)}</article>`).join(''):empty('What would you like to save for?','An emergency fund, your next trip, or something entirely yours.',button('Create your first goal','add-goal','plus','mn-primary'),'target')}</div><p class="mn-panel-note">Goal funds stay inside your savings allocation. Assigning or releasing them does not change your total balance.</p>`;
}
export function page(data,state) {
  const titles={overview:['Money Overview','A clearer picture of your everyday finances.'],transactions:['Transactions','Keep track of where every baht goes.'],budgets:['Monthly Budgets','Spend with intention. Leave room for what matters.'],goals:['Savings Goals','Small steps toward the things you care about.'],subscriptions:['Subscriptions','Keep regular commitments visible before they renew.']};
  const [title,subtitle]=titles[state.tab];
  return `<div class="mn-wrap"><div class="mn-topbar"><button type="button" class="mn-wordmark" data-action="overview"><span class="mn-brand" aria-hidden="true"><i></i><i></i><i></i></span>Moatrices<span>MONEY</span></button><div class="mn-topbar-right"><span>${icon('shield')}Personal workspace</span>${miniButton('Money settings','settings','settings')}</div></div><header class="mn-page-head"><div><span class="mn-kicker">YOUR MONEY, WITH PERSPECTIVE</span><h1>${title}<span>.</span></h1><p>${subtitle}</p></div><div class="mn-head-actions"><div class="mn-month-picker">${miniButton('Previous month','prev','left')}<input type="month" aria-label="Selected month" data-control="month" value="${state.month}" max="${localDate().slice(0,7)}">${miniButton('Next month','next','right',state.month>=localDate().slice(0,7)?'disabled':'')}</div>${button('Add transaction','add','plus','mn-primary')}</div></header><nav class="mn-tabs" aria-label="Money sections">${TABS.map(([id,label,glyph])=>`<button type="button" data-action="${id}" ${id===state.tab?'aria-current="page"':''}>${icon(glyph)}${label}</button>`).join('')}</nav><div class="mn-notifications" aria-live="polite">${state.message?`<div class="mn-notice ${state.error?'mn-inline-warning':''}" ${state.error?'role="alert"':''}>${icon(state.error?'flag':'check')}<span>${esc(state.message)}</span>${miniButton('Dismiss message','dismiss','close')}</div>`:''}</div><div class="mn-content">${state.tab==='overview'?overview(data,state):state.tab==='transactions'?transactions(data,state):state.tab==='budgets'?budgets(data,state):state.tab==='goals'?goals(data):subscriptions(data,state)}</div><footer class="mn-footer"><span><i></i>MOATRICES · MONEY</span><span>Amounts in THB · Your recorded transactions</span><span>A little clarity, every day.</span></footer><input class="mn-sr-only" type="file" accept=".csv,text/csv" data-csv-input aria-label="Import transactions CSV" tabindex="-1"></div>`;
}
